---
title: "IS IT SAFE TO BOAT?"
author: "Peter Olsen"
date: "October 28, 2016"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## The River
The Mystic River is located in the Boston, Massachusetts area.   Like many urban rivers it struggles with water quality issues.  In recent years, a lot of effort has been put into cleaning it up and maintain it as a quality watershed for recreational use as well as to meet environmental goals.

## Boating
The Mystic River is safe for boating/kayaking most of the time.  Sometimes unsafe levels of E. coli bacteria are recorded.  One predictor of these unsafe conditions is the amount of rain that has occurred in the last 48 hours.  
  
This project allows the public to enter the amount of rain that has recently occurred and check if conditions on the river are estimated to be safe enough for recreational boating or if they should put off plans until another time.  
  
Unsafe conditions are highlighted in RED.  

The App:  
https://arcticgrayling.shinyapps.io/IsTheWaterSafe/


## Technical details

  The site uses linear models with data collected in 2015 to predict bacterial levels based on precipitation amounts in the last 48 hours.  In addition to the linear models running in R, code was written in shiny to highlight certain conditions with color.  

###E. coli levels  

- Color Blue: under 235/100ml; considered safe for boating and swimming.  
- Color Yellow:  over 235/100ml but below 1260/100ml; considered safe for boating but not swimming.  
- Color Red: over 1260/100ml;  considered unsafe for all recreational activity on the river.  
   
####The code  
The Code can be found on git hub at: 

https://github.com/Arcticgrayling/IsItSafeToBoat
  
## Other
- Disclaimer: 
This site uses preliminary data and prediction models, it is for educational and demonstration purposes only.  For more information about the Mystic River and water quality, got to http://mysticriver.org/

